name: lme-docs

services:
  server:
    image: ghcr.io/gohugoio/hugo:v0.147.8
    command: serve --disableFastRender 
    volumes:
      - ./:/project
      - ~/hugo_cache:/cache
    ports:
      - 1313:1313

