/**
 * @decision DEC-006
 * @title Autogenerated sidebars from filesystem
 * @status accepted
 * @rationale Ludus pattern — _category_.json files drive ordering and labels.
 *            Eliminates manual sidebar maintenance as docs grow.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
